### ISSUE TITLE
MakeMKV apparently does not work with openjdk11.

### ISSUE THREAD

**Issue by parasense** [flathub/com.makemkv.MakeMKV#25]
Please see here:
https://www.makemkv.com/forum/viewtopic.php?t=18879

With the bundled version of openjdk11 we see the following error in the debug log:
```
...
003344:0000 Using Java runtime from /app/jre/bin/java
java_exception(6) : java.lang.NullPointerException
java.lang.NullPointerException
	at com.makemkv.Runtime.a(Unknown Source)
	at com.makemkv.Runtime.b(Unknown Source)
	at com.makemkv.g.action(Unknown Source)
	at blues.Server.actionInvoke(Server.java:245)
	at blues.Server.access$000(Server.java:33)
	at blues.Server$1.run(Server.java:196)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
...
```

According to the MakeMKV forums the older java 1.8 should be used instead.
Perhaps the "sdk org.freedesktop.Sdk.Extension.openjdk8" could be used instead?

That said, I tried to configure an override so MakeMKV points at my system-wide java.
```
sudo flatpak override --filesystem=/usr/lib/jvm/ com.makemkv.MakeMKV
```

And, then of course configuring MakeMKV preferences accordingly to use "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-1.fc32.x86_64/jre/bin/java"

But that doesn't work either, the log goes like this:
```
004041:0000 Failed to execute external program 'java' from location '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-1.fc32.x86_64/jre/bin/java'
```

Does anybody have an idea of a way forward?

**Comment by parasense** [comment]
In theory this patch would be the starting point
```
diff --git a/com.makemkv.MakeMKV.json b/com.makemkv.MakeMKV.json
index e5df569..b005b40 100644
--- a/com.makemkv.MakeMKV.json
+++ b/com.makemkv.MakeMKV.json
@@ -5,7 +5,7 @@
   "sdk": "org.kde.Sdk",
   /* NOTE: java is optional to help find blu-ray main titles */
   "sdk-extensions": [
-    "org.freedesktop.Sdk.Extension.openjdk11"
+    "org.freedesktop.Sdk.Extension.openjdk8"
   ],
   "finish-args": [
     "--filesystem=host",
@@ -20,7 +20,7 @@
   ],
   "command": "makemkv",
   "build-options" : {
-    "append-path": "/usr/lib/sdk/openjdk11/bin"
+    "append-path": "/usr/lib/sdk/openjdk8/bin"
   },
   "rename-desktop-file": "makemkv.desktop",
   "rename-icon": "makemkv",
@@ -34,7 +34,7 @@
       "name": "openjdk",
         "buildsystem": "simple",
         "build-commands": [
-          "/usr/lib/sdk/openjdk11/install.sh"
+          "/usr/lib/sdk/openjdk8/install.sh"
         ]
     },
     {
```

A few remarks:
* This was my first time ever rebuilding any flatpak with `flatpak-builder`, and the result was not great despite the patch being so trivial. By "not great" I mean the app launches, but then hangs without much indication as to why, specifically clicking "open files" causes the hang.
* Here is my basic build procedure:
(can somebody please help me reproduce the flathub "production" build, so I might develop a working contribution?)
```
git clone https://github.com/flathub/com.makemkv.MakeMKV.git
pushd com.makemkv.MakeMKV
mkdir builddir $HOME/myflatapps
git apply ${HOME}/makemkv_openjdk8.diff
flatpak-builder --force-clean --repo=${HOME}/myflatapps  builddir/ com.makemkv.MakeMKV.json
popd
flatpak remote-add --no-gpg-verify --prio=99 myflatapps ${HOME}/myflatapps
flatpak install myflatapps com.makemkv.MakeMKV
flatpak run --verbose --ostree-verbose com.makemkv.MakeMKV
flatpak enter $(flatpak ps --columns=instance | awk '!/Instance/ {print ;exit}' ) bash
```

* The openjdk8 appears to introduce  unwanted java binaries compared to openjdk11, stuff besides jar, java, keytool, etc... like 15 ~25 additional items in the `/app/jre/bin/` directory.
```
[📦 com.makemkv.MakeMKV com.makemkv.MakeMKV]$ ls /app/jre/bin
appletviewer  javadoc	    jhat	jstatd	      schemagen
clhsdb	      javah	    jinfo	keytool       serialver
extcheck      javap	    jjs		native2ascii  servertool
hsdb	      java-rmi.cgi  jmap	orbd	      tnameserv
idlj	      jcmd	    jps		pack200       unpack200
jar	      jconsole	    jrunscript	policytool    wsgen
jarsigner     jdb	    jsadebugd	rmic	      wsimport
java	      jdeps	    jstack	rmid	      xjc
javac	      jfr	    jstat	rmiregistry
```


Thanks for reading this far.

**Comment by parasense** [comment]
Java does not fail with "java.lang.NullPointerException" using #26 
However, I'm not sure how well the feature actually works from MakeMKV perspective. 
I'm able to load a few titles known to cause java to load, and no more "java.lang.NullPointerException", but not very great title detection, or possibly no smart title detection.

**Comment by wberrier** [comment]
Seems like an improvement to me, thanks for testing
