### ISSUE TITLE
1.16.4 Beta version in Flatpak is outdated

### ISSUE THREAD

**Issue by cassidyjames** [flathub/com.makemkv.MakeMKV#33]
I get an error upon running, and then it closes:

>This application version is too old.  Please download the latest version at http://www.makemkv.com/ or enter a registration key to continue using the current version.

It looks like 1.16.5 is the latest as of posting: https://forum.makemkv.com/forum/viewtopic.php?f=3&t=224

**Comment by wberrier** [comment]
Fixed in #31
