### ISSUE TITLE
Can't Integrate With VLC

### ISSUE THREAD

**Issue by RedSoxFan04** [flathub/com.makemkv.MakeMKV#34]
I had no trouble with integration when I installed "manually" with the _bin_ and _oss_ folders, but ever since I uninstalled that version and installed the Flatpak, I've been unable to play Blu-Rays with VLC.

I should probably mention that I'm running Debian 11 (Bullseye).

**Comment by wberrier** [comment]
I think if you install the following flatpaks:

* org.videolan.VLC.Plugin.makemkv
* com.makemkv.MakeMKV
* org.videolan.VLC

and then register the makemkv, blurays will work with the vlc flatpak version (at least, worked on my fedora 34 system).

**Comment by RedSoxFan04** [comment]
> I think if you install the following flatpaks:
> 
>     * org.videolan.VLC.Plugin.makemkv
> 
>     * com.makemkv.MakeMKV
> 
>     * org.videolan.VLC
> 
> 
> and then register the makemkv, blurays will work with the vlc flatpak version (at least, worked on my fedora 34 system).

I just went to install org.videolan.VLC.Plugin.makemkv, but I got this:
`Note that the directory 

'/root/.local/share/flatpak/exports/share'

is not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

Looking for matches…
Remotes found with refs similar to ‘org.videolan.VLC.Plugin.makemkv’:

   1) ‘flathub’ (system)
   2) ‘flathub’ (user)
`

Which should I pick?

**Comment by RedSoxFan04** [comment]
> I think if you install the following flatpaks:
> 
>     * org.videolan.VLC.Plugin.makemkv
> 
>     * com.makemkv.MakeMKV
> 
>     * org.videolan.VLC
> 
> 
> and then register the makemkv, blurays will work with the vlc flatpak version (at least, worked on my fedora 34 system).

Thanks!

**Comment by RedSoxFan04** [comment]
> > I think if you install the following flatpaks:
> > ```
> > * org.videolan.VLC.Plugin.makemkv
> > 
> > * com.makemkv.MakeMKV
> > 
> > * org.videolan.VLC
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then register the makemkv, blurays will work with the vlc flatpak version (at least, worked on my fedora 34 system).
> 
> It worked! Thanks! Though, it turns out that if you want to use Blu-Ray menus, you need to install org.videolan.VLC.Plugin.bdj.

**Comment by wberrier** [comment]
Sounds like this can be closed?

**Comment by TheNamelessWonderer** [comment]
can it be made to work with the non flatpak VLC?

**Comment by RedSoxFan04** [comment]
> Sounds like this can be closed? (reopen if that's not the case)

Yeah, it can.

**Comment by RedSoxFan04** [comment]
> can it be made to work with the non flatpak VLC?

Unfortunately, no. I ended up having to install the Flatpak. However, to my surprise, it works perfectly.
