### ISSUE TITLE
MakeMKV 1.16.7 publishing failure

### ISSUE THREAD

**Issue by develop7** [flathub/com.makemkv.MakeMKV#39]
The #38 has been merged but https://flathub.org/apps/details/com.makemkv.MakeMKV still indicates 1.16.5.

**Comment by wberrier** [comment]
I think this has happened before, and I had to go and manually start
another build.

I'll see what I can do.

**Comment by wberrier** [comment]
Looks like it worked:

https://flathub.org/builds/#/builders/32/builds/81863
