### ISSUE TITLE
How to use the CLI version of MakeMKV?

### ISSUE THREAD

**Issue by 07416** [flathub/com.makemkv.MakeMKV#43]
the developer documentation: https://makemkv.com/developers/usage.txt

**Comment by lhw** [comment]
You can use the makemkvcon cli like this with this flatpak `flatpak run --command=makemkvcon com.makemkv.MakeMKV` there is no extra cli flatpak as of yet. But works fine

**Comment by 07416** [comment]
> You can use the makemkvcon cli like this with this flatpak `flatpak run --command=makemkvcon com.makemkv.MakeMKV` there is no extra cli flatpak as of yet. But works fine

So it seems, I didn't expect an alternative version.
