### ISSUE TITLE
MakeMKV 1.17.3 released on 2023-02-01and now 1.17.2 crashes on launch

### ISSUE THREAD

**Issue by colinscroggins** [flathub/com.makemkv.MakeMKV#47]
Application displays a notice of new version release at launch and then crashes and fails to respond until Fedora prompts to force quit.

Running on Fedora 37 Workstation.

**Comment by michaelkuhn** [comment]
Do you get an error message, a backtrace or something similar?

I'm also using Fedora 37 Workstation but 1.17.2 still works for me. :thinking:

**Comment by colinscroggins** [comment]
@michaelkuhn Do you already have a registration code input? I did not on this install and even after completely removing the flatpak and reinstalling, I still have the same issue.

On initial app launch, I do not get an actual error, just the notice of new version and then an immediate OS prompt to wait or kill hung process. The app interface is non-responsive, so I cannot enter the registration code to see if that makes a difference.

**Comment by michaelkuhn** [comment]
Yes, I've already entered a key. Maybe you can work around it by putting the key into the config file like described here: https://forum.makemkv.com/forum/viewtopic.php?t=1359
