### ISSUE TITLE
Please update to 1.17.7

### ISSUE THREAD

**Issue by esa1975** [flathub/com.makemkv.MakeMKV#82]
Hello. Thanks for your time maintaining this project. I received an error message when starting the app to please update or register. The current version is 1.17.7. Please update this when you have a chance. Thanks!

**Comment by autovettore** [comment]
Is there a reason why the pull request cannot be merged? (The build seems to have been successful)

**Comment by michaelkuhn** [comment]
I just merged #80, 1.17.7 should be available soon.
