### ISSUE TITLE
The program can't find any usable optical drives.

### ISSUE THREAD

**Issue by Alerymin** [flathub/com.makemkv.MakeMKV#94]
I just installed the flatpak. It used to work fine but now it does not with this error:

`The program can't find any usable optical drives.`

Note that the version of the flatpak is MakeMKV v1.17.7 which is not the latest version

**Comment by Alerymin** [comment]
Update: Issue not specific to flatpak, closing

**Comment by Cwavs** [comment]
I've started hitting this issue. I know it's not flatpak exclusive, but did you ever find a solution? The drive has worked previously and I can't find anyone else with this issue. @Alerymin

**Comment by Alerymin** [comment]
@Cwavs I don't remember at all what I did, I think it was a library I forgot to install

**Comment by Cwavs** [comment]
Thanks, I'll have a look around then and see if I can find it.

**Comment by Alerymin** [comment]
@Cwavs thanks for the reminder, I forgot that I had to do this too. This was my issue

**Comment by Cwavs** [comment]
@Alerymin No Problem!
